### ISSUE TITLE
Document running tests on catkin packages

### ISSUE THREAD

**Issue by paulbovbel** [colcon/colcon.readthedocs.org#29]
Doing a bit of experimenting, I've found that running test on catkin packages isn't quite as straightforward as `colcon build && colcon test`. It's not immediately obvious, but one has to run:

```
colcon build --cmake-target tests
colcon test
```

...as extracted from https://github.com/ros-infrastructure/ros_buildfarm/pull/548,

---

I'm guessing this is my fault, but I've found that when I attach a DEPENDENCY to `catkin_add_nosetests` such as when using `catkin_virtualenv` (https://github.com/paulbovbel/test_meta/blob/master/CMakeLists.txt#L52), I have to run the following to get all tests to pass:

```
colcon build
colcon build --cmake-target tests
colcon test
```

Even though it looks like the `${PROJECT_NAME}_generate_virtualenv` should be getting hooked in via the underlying catkin mechanisms.

**Comment by dirk-thomas** [comment]
In `catkin` packages test targets are usually created with the [EXCLUDE_FROM_ALL](https://cmake.org/cmake/help/v3.0/prop_tgt/EXCLUDE_FROM_ALL.html) flag. Therefore they are not being built by a normal `cmake --build` invocation. To the second snippet (`colcon build`, `colcon build --cmake-target tests`, `colcon test`) is the right "generic" approach.

Can you create a pull request to update the documentation accordingly?

**Comment by paulbovbel** [comment]
Done https://github.com/colcon/colcon.readthedocs.org/pull/30

Although I wonder if for consistencies sake, it wouldn't make sense to supress EXCLUDE_FROM_ALL behaviour when building from ROS via colcon.

**Comment by dirk-thomas** [comment]
> it would make sense to suppress EXCLUDE_FROM_ALL behaviour when building from ROS via colcon

I don't think there is (currently?) a way  to override that from the "outside". The argument is hard coded in the CMake code (e.g. the catkin function to add tests) but potentially also in the package specific CMake code. If you can imagine a way I would be happy to consider it.
