### ISSUE TITLE
github workflow fails because of missing pyenchant

### ISSUE THREAD

**Issue by rkent** [colcon/colcon.readthedocs.org#97]
The github workflow for this fails because pyenchant cannot be found. It can be fixed by installing through apt, see [this commit](https://github.com/colcon/colcon.readthedocs.org/commit/a326fc6ef0a55b3e9fa20bb4fe38b490407f69f7). I can submit this as a PR if you want, but I don't know if the github workflow still matters on this.

:rkent

**Comment by nuclearsandwich** [comment]
Thanks for the report. I believe this has been resolved with #99 and #100.
